/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'raulcd' at '13/08/15 21:45' with Gradle 2.6
 *
 * @author raulcd, @date 13/08/15 21:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
